### ISSUE TITLE
Is it possible to do drag&drop of chips?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [BelooS/ChipsLayoutManager#11]
As the title ...

**Comment by BelooS** [comment]
Sure, but it is out of library scope. It doesn't differs from [for example GridLayoutManager](http://stackoverflow.com/questions/29901044/drag-and-drop-items-in-recyclerview-with-gridlayoutmanager) drag'n'drop solutions.

Actually i haven't tried it yet. You may :)

**Comment by AndroidDeveloperLB** [comment]
Can you please add it as a feature?
Maybe "setEnableDragNDrop(boolean)" ?

**Comment by BelooS** [comment]
It isn't responsibility of `LayoutManager`. It may only place view on layout, but can't control particular view behaviour (e.g. `RecyclerView`). It should be managed outside. 

You could try for example a combination of [AdvancedRecyclerView](https://github.com/h6ah4i/android-advancedrecyclerview) and this library to implement required feature. And share with us results.

PS: Maybe i'll provide such issue as a bonus to the library, which would be implemented in a sample, but it isn't in priority for today.

**Comment by AndroidDeveloperLB** [comment]
Thank you
