### ISSUE TITLE
Support Gravity.FILL

### ISSUE THREAD

**Issue by mvarnagiris** [BelooS/ChipsLayoutManager#13]
It would be nice if we could fill the whole width of the line. It would also be nice if we could do it two ways

1. Add more spacing
2. Increase the width of the items.

**Comment by BelooS** [comment]
It is currently possible. You can set item's `layout_width` to `match_parent` and that item will fill the whole line. 
'spacing' filling you may achieve with breaker, just mark that target view & previous one breaks row. Or even easier with wrapping item in transparent container with `match_parent` width.

**Comment by mvarnagiris** [comment]
Thanks for quick response. What you suggesting is not what I mean. Sorry I should have been more specific. I want something like this
`aaa-aa-aaaa-aa`
`a---aaaaa---aa`
`aaaaaaaaaa--aa `

**Comment by BelooS** [comment]
Ok, i see now. 
I'll think about implementation

**Comment by BelooS** [comment]
Have been implemented in `0.3.1`. Improvements will depend on some user cases. I've tried to cover possible required options, but still.

**Comment by mvarnagiris** [comment]
I just tested this out. Works great! Thanks.
