### ISSUE TITLE
Possibility to check if scrolled to top

### ISSUE THREAD

**Issue by MFlisar** [BelooS/ChipsLayoutManager#14]
Can I find out, if the `ChipsLayoutManager` is scrolled to top or not? Is this currently supported?

**Comment by BelooS** [comment]
So strange that `findLastVisibleItemPosition` and analogue methods isn't implemented in base class. So i'm going to implement it in the next version of layout manager.

**Comment by MFlisar** [comment]
Perfect, thanks. that was exactly the function I was looking for.

**Comment by BelooS** [comment]
Have implemented in `0.3.1`.

**Comment by MFlisar** [comment]
That was fast, thanks. Just tested it and it seems to work.
