### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by santhosh153** [BelooS/ChipsLayoutManager#19]
When i  am scrolling fast  the recyclerview is showing some extra space either on top or in the middle

**Comment by BelooS** [comment]
Could you provide additional details like screenshot/video or smth? And your setup of `ChipsLayoutManager`. I am not able to reproduce it on my own.

**Comment by santhosh153** [comment]
its a sample application that you have provide 
[
(![error](https://cloud.githubusercontent.com/assets/6703954/21219088/50806d88-c2d9-11e6-9270-e9091b48c130.png))
](url) 
[
![error_1](https://cloud.githubusercontent.com/assets/6703954/21219129/70c40b5e-c2d9-11e6-8b22-dcef1e94c0b1.png)
](url)

**Comment by BelooS** [comment]
Thanks for feedback, but how have you received that... a bit wierd, that i still haven't repeated it. What android-api have you run on? Was it last master branch fork (v0.3.4)? Should i just quickly scroll forward/backward to reproduce it without any other actions?

**Comment by santhosh153** [comment]
I am running  the app on android os 6.0 and try to scroll multiple times from starting  to end of the view

**Comment by BelooS** [comment]
Maybe your android studio somehow cached lib and don't update it. Try clean build & cache clean. This bug was actual in some of the middle versions, but seems the last one is correct.
