### ISSUE TITLE
Set items which move to next line

### ISSUE THREAD

**Issue by AleksandrKrasnoperov** [BelooS/ChipsLayoutManager#2]
Hi. Can I set items which move to next line?

**Comment by BelooS** [comment]
Do you mean an item, which always breaks line? 
You can't with current revision, but it's good feature request.
It will be provided with future releases, wait for updates

**Comment by AleksandrKrasnoperov** [comment]
Yes.
Ok. Thx. I'll wait.

**Comment by BelooS** [comment]
Have implemented in 0.2.1
