### ISSUE TITLE
onLayout get called again and again

### ISSUE THREAD

**Issue by hubcin** [BelooS/ChipsLayoutManager#20]
the method `onLayoutChildren` seems getting called again and again, which seems so abnormal.

**Comment by BelooS** [comment]
Thanks for feedback. Unfortunately i haven't tested it well with small amount of items. I'm going to fix & provide functional test for this case

**Comment by hubcin** [comment]
Thank you for providing this, I have used it in my project and it works well. As to some little bugs, I will help you spot them.

**Comment by BelooS** [comment]
fixed in 0.3.4.1. Just an intermediate version for this bugfix, coz it really makes me unhappy)
