### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by hubcin** [BelooS/ChipsLayoutManager#22]
`java.lang.IllegalStateException: Observer com.beloo.widget.chipslayoutmanager.layouter.MeasureSupporter@6c0f5aa is already registered.`

When I call `setAdapter` the second time for my RecyclerView which has ChipsLayoutManager, it will give me this error.

**Comment by hubcin** [comment]
I think you would have to remove the first line in function `onAdapterChanged()`, because when `setAdapter` of the `RecyclerView` called, the data observer is already registered. 
Didn't figure out why you explicitly registered it again, so if registering it is necessary in some circumstances, I think you may have to check if the data observer is registered or not before that.

**Comment by BelooS** [comment]
Yes, this issue goes into more deeper problem, coz in case changing adapters - layout manager will listen for both of them with current implementation, which is really incorrect. Thanks again for nice feedback

**Comment by BelooS** [comment]
fixed in v0.3.5. Covered with functional test

**Comment by hubcin** [comment]
👍  👍 👍

**Comment by hubcin** [comment]
Yeah, it's perfectly done. Had to clean the project and rebuild it after changing to the newer version. Thanks for you efforts.

**Comment by BelooS** [comment]
np
