### ISSUE TITLE
is it possible to add header/footer to each break?

### ISSUE THREAD

**Issue by Manuiq** [BelooS/ChipsLayoutManager#28]
here is what I'm trying to achieve http://imgur.com/a/3Hkho

**Comment by Oleg-Beloy** [comment]
I am afraid that it isn't possible with _clm_. 
You may achieve it with pre-calculations and horizontal `GridLayoutManager`. Assuming that you have static height of items in list, static height of footer/header, having height of screen you'll able to calculate count of fitting items, split input sequence to pieces of that count and than display it with inner `RecyclerView`. With dynamic heights it will me more tricky, but possible. That's my suggestion

**Comment by Manuiq** [comment]
I'll try it out, thanks
