### ISSUE TITLE
Scrolling gets stuck on second to last row when no padding on recyclerview

### ISSUE THREAD

**Issue by jasennett** [BelooS/ChipsLayoutManager#40]
If there is no padding on the RecyclerView using the ChipsLayoutManager, you will not be able to scroll past the second to last row under the following scenario:
- Scroll down to the last row
- Scroll up past the last row so that the second to last row is the last visible row in the RecyclerView
- Attempt to scroll down to the last row
At this point the RecyclerView will not scroll past the second to last row.  This behavior also occurs with columns when using the horizontal orientation setting.

**Comment by Oleg-Beloy** [comment]
closed according to your pr, will be released asap
