### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by MFlisar** [BelooS/ChipsLayoutManager#5]
* gradle import is not working - even after adding ` maven { url "http://dl.bintray.com/beloo/widget" } `
* if I download your project and use it in my app, the `id "me.tatarka.retrolambda" version "3.3.1"` is interfering with the definition in my project. I think this plugin should be defined in the root project, not in the library project
* I'm using timber myself, so this is no problem for me, but I suggest removing timber from the library. It's an unnecessary extra dependency...

**Comment by BelooS** [comment]
I'll check it, ty

**Comment by MFlisar** [comment]
I'm using `retrolambda` as well, but yes, I would remove it from a library (I do the same in my open source libraries)

And yes, `jcenter` reference is existing...

**Comment by BelooS** [comment]
You could use updated dependency for gradle support. Also i accepted your suggestions and have cleaned up this library, so retrolambda and timber dependency will be removed from next release.

**Comment by MFlisar** [comment]
Thanks. Dependency is working now.

**Comment by BelooS** [comment]
All issues solved in 0.2.4.
