### ISSUE TITLE
Could not find library

### ISSUE THREAD

**Issue by iammert** [BelooS/ChipsLayoutManager#6]
I believe that I correctly setup library but gradle could not find library. I already tried jitpack. Same result. Can you fix that.

**Comment by BelooS** [comment]
Sure, i am going to check it

**Comment by iammert** [comment]
Thanks for quick response. Looking forward.

**Comment by BelooS** [comment]
By the way, do you have jcenter() repository reference, not just mavenCentral()? Because this library is uploaded only to jCenter.

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by ericcarboni** [comment]
I am having the same problem, using jcenter() as well. Glad it's not just me!

> Could not find `com.beloo.widget:ChipsLayoutManager:0.2.2`

**Comment by iammert** [comment]
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
        maven { url "https://jitpack.io" }
    }
}
```

Yes, I added jcenter() too. I made it work by adding library as module. But I will be happy If you can fix jcenter issue.

**Comment by BelooS** [comment]
I see. So strange, i'll try to handle it soon

**Comment by BelooS** [comment]
You could use `compile 'com.beloo.widget:ChipsLayoutManager:0.2.2:release@aar'` as a temporary solution. In next versions it may be simplified.

**Comment by iammert** [comment]
I will try and let you know.

**Comment by ericcarboni** [comment]
That solved the issue, thanks @BelooS!
