### ISSUE TITLE
RecyclerView height wrap_content

### ISSUE THREAD

**Issue by whitipet** [BelooS/ChipsLayoutManager#8]
So my problem is what when I use `android:layout_height="wrap_content"` for my RecyclerView, he just cut off instead of expanding. Or I doing something wrong or it is just a bug.

**Comment by BelooS** [comment]
Could you check it with sample? I have created [a branch](https://github.com/BelooS/ChipsLayoutManager/tree/test/height_wrap_content)  for you with such `RecyclerView`. It is working here. 

Seems your issue is more specific and i need additional details. Something which is not default

**Comment by whitipet** [comment]
Hm, I checked the branch and all look great. Maybe my problem in parent ScrollView.
My layout look like this
```
<ScrollView>
    <!--some content-->
    <android.support.v7.widget.CardView>
        <LinearLayout>
            <TextView>
            <LinearLayout>
                <android.support.v7.widget.RecyclerView> <!--I use this RecyclerView-->
                <ImageView>
            </LinearLayout>
         </LinearLayout>
     </android.support.v7.widget.CardView>
</ScrollView>
```

**Comment by whitipet** [comment]
After some experiments I can say that problem in ScrollView and ChipsLayoutManager. When I use LinearLayoutManager all looks great.

**Comment by BelooS** [comment]
Just wrapping `RecyclerView` in ScrollView doesn't break behaviour. 
Could you share a full layout? 

Also consider using `android.support.v4.widget.NestedScrollView` instead of `ScrollView`, because it is more compatible with `RecyclerView`. 
Also try with newest 0.2.4 layout manager, it may help.

**Comment by whitipet** [comment]
Ok, I will try. Thanks for fast response.

**Comment by BelooS** [comment]
Any updates? I wanna close the issue.

**Comment by whitipet** [comment]
I have jumped to another library. Perhaps problem was in my code. I think you can close issue. If something goes wrong again I will write you. Thank for communication.
