### ISSUE TITLE
How to get row counts in ChipsLayoutManager?

### ISSUE THREAD

**Issue by YiChaoLove** [BelooS/ChipsLayoutManager#9]
Hello, thank your ChipsLayoutManager  and I want to know that is there any method can get row counts in layoutManger?

**Comment by BelooS** [comment]
It's impossible to get count of rows. It depends on restriction that you could know an exact position of view only if you previously calculated all views before it. So all views inside layout would have to be recalculated from scratch or in case data changes for correct implementation of this method. That breaks `RecyclerView` purpose.

**Comment by YiChaoLove** [comment]
OK, thank you. But, can we listen LM break row?
